# Generated by Django 3.1.7 on 2021-06-03 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(default='', max_length=100)),
                ('code_color', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=100)),
                ('value', models.FloatField(default=0)),
                ('phantram', models.IntegerField(default=0)),
                ('max_value', models.FloatField(default=0)),
                ('min_price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('image_main_product', models.ImageField(upload_to='')),
                ('describe', models.TextField(default='sản phẩm này rất sịn sò')),
                ('type', models.CharField(default='defau', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('number_phone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.product')),
                ('category', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
            ],
            bases=('user.product',),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.product')),
                ('material', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
            ],
            bases=('user.product',),
        ),
        migrations.CreateModel(
            name='Product_Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('discount', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.discount')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('color', models.CharField(default='default color', max_length=20)),
                ('size', models.CharField(default='default size', max_length=20)),
                ('total', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product')),
            ],
        ),
        migrations.CreateModel(
            name='InforOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('payment', models.CharField(default='Thanh toán khi nhận hàng', max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('receiveDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('amount', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('statusstr', models.CharField(default='đang chờ xác nhận', max_length=100)),
                ('process', models.IntegerField(default=25)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.product')),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.product')),
                ('supplier', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.supplier')),
            ],
            bases=('user.product',),
        ),
        migrations.CreateModel(
            name='Clothes_Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.size')),
                ('clothes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.clothes')),
            ],
        ),
    ]
