# Generated by Django 3.1.7 on 2021-06-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.infororder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.itemincart')),
            ],
        ),
    ]
