# Generated by Django 3.1.7 on 2021-06-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210612_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clothes_Size',
        ),
    ]
