# Generated by Django 3.1.7 on 2021-06-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_clothes_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemincart',
            name='account',
        ),
    ]
