# Generated by Django 3.1.7 on 2021-06-12 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_itemincart_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemincart',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.infororder'),
        ),
    ]
