# Generated by Django 3.1.7 on 2021-06-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210612_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('villate', models.CharField(default='', max_length=100)),
                ('number_house', models.CharField(default='', max_length=100)),
                ('number_phone', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
