# Generated by Django 3.1.7 on 2021-06-12 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_receiveaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveaddress',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
        ),
    ]
