# Generated by Django 3.1.7 on 2021-06-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_infororder_receive_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='infororder',
            name='receive_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.receiveaddress'),
        ),
    ]
