# Generated by Django 3.1.7 on 2021-06-15 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('import_price', models.FloatField(default=0)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.product')),
            ],
        ),
        migrations.CreateModel(
            name='BillStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('import_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.supplier')),
            ],
        ),
    ]
