from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Product)
admin.site.register(Image)
admin.site.register(Color)
admin.site.register(Product_Color)
admin.site.register(Book)
admin.site.register(Clothes)
admin.site.register(Electronic)
admin.site.register(Size)
admin.site.register(Supplier)
admin.site.register(Discount)
admin.site.register(Product_Discount)
admin.site.register(Shipment)
admin.site.register(Order_Item)
admin.site.register(InforOrder)
admin.site.register(Category)
admin.site.register(Author)
admin.site.register(FullName)
admin.site.register(Address)
admin.site.register(Customer)
admin.site.register(ItemInCart)
admin.site.register(ReceiveAddress)
admin.site.register(Payment)
admin.site.register(Comment)
admin.site.register(Loves)
admin.site.register(Rating)
admin.site.register(Chat)
admin.site.register(Types)
admin.site.register(Brand)
admin.site.register(Material)
admin.site.register(Store)
admin.site.register(BillStore)
